"""在庫管理（Streamlit Cloud 向けパッケージ）。"""

from stock_inventory.logic import (
    add_delivery,
    apply_planned_consumption,
    build_inventory_projection,
    clear_consumption_plan,
    clear_delivery_plan,
    days_until_stockout,
    delete_delivery,
    get_delivery_weekdays,
    init_consumption_plan_csv,
    init_deliveries_csv,
    init_delivery_plan_csv,
    init_inventory_csv,
    load_deliveries_df,
    load_inventory_df,
    load_manual_planned_use,
    save_consumption_plan,
    save_delivery_plan,
    save_delivery_weekdays,
    save_product_inventory,
    sync_inventory_products,
    weekday_labels_text,
)

__all__ = [
    "add_delivery",
    "apply_planned_consumption",
    "build_inventory_projection",
    "clear_consumption_plan",
    "clear_delivery_plan",
    "days_until_stockout",
    "delete_delivery",
    "get_delivery_weekdays",
    "init_consumption_plan_csv",
    "init_deliveries_csv",
    "init_delivery_plan_csv",
    "init_inventory_csv",
    "load_deliveries_df",
    "load_inventory_df",
    "load_manual_planned_use",
    "save_consumption_plan",
    "save_delivery_plan",
    "save_delivery_weekdays",
    "save_product_inventory",
    "sync_inventory_products",
    "weekday_labels_text",
]
